### ISSUE TITLE
System.ArgumentNullException on Async Post

### ISSUE THREAD

**Issue by jnhaffey** [feinoujc/Mandrill.net#117]
After upgrading to 7.3 started getting this exception when attempting to send an email to mandrill via SentTemplateAsync method.

`
Call to Mandrill failed: "System.ArgumentNullException: Value cannot be null.
Parameter name: o
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Mandrill.Serialization.MandrillMergeVarConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Mandrill.MandrillRequest.GetStreamContent[T](T value, StreamWriter writer)
   at Mandrill.MandrillRequest.PostAsJsonAsync[T](String requestUri, T value, CancellationToken c)
   at Mandrill.MandrillRequest.PostAsync[TRequest,TResponse](String requestUri, TRequest value)
   at Core.Providers.Mandrill.MandrillProvider.SendEmailToProviderUsingMandrill(EmailRequestMessage message, CancellationToken token, Func`4 providerResponseHandler)"
`

When I downgrade to 7.2 this issue goes away.

**Comment by feinoujc** [comment]
Is the content in one of our merge variables `null`? 

(that's what it looks like, just want to confirm)

**Comment by feinoujc** [comment]
fixed in #118
