### ISSUE TITLE
Use of attachments

### ISSUE THREAD

**Issue by alphaklp** [feinoujc/Mandrill.net#74]
when I attach a byte[] to a Mandril message using 

            var pdf = new MandrillAttachment("application/pdf", "Invoice", dataArray);
            
            message.Attachments.Add(pdf);
             await MandrillApi.Messages.SendTemplateAsync(message, TemplateName);

I get a pretty nasty error 
Exception Info: System.Net.Http.HttpRequestException
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Mandrill.MandrillRequest+<EnsureSuccessAsync>d__10.MoveNext()

Exception Info: Mandrill.Model.MandrillException
   at Mandrill.MandrillRequest+<EnsureSuccessAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Mandrill.MandrillRequest+<PostAsync>d__9`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at Lakrids.Commerce.Notifications.Messages.Message+<Send>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

I did NOT base64 encode the attachment - that is done by the API right? 
Should attachments be supported?

**Comment by alphaklp** [comment]
I have tested this further - and it does not always happen. If I use a small text attachment it works - but a 1 MB PDF attachment breaks

**Comment by feinoujc** [comment]
Hi @alphaklp what version are you running? I am not able to reproduce this. I can make it error if I exceed the max message size https://mandrill.zendesk.com/hc/en-us/articles/205582407-Does-Mandrill-Support-Attachments-

Any chance your message is that big? How many attachments are you adding?

**Comment by alphaklp** [comment]
I have one attachment at approx 1 MB running version 4.1. 
It is runinng .NET core

**Comment by feinoujc** [comment]
Can you print more information about the error? specifically the message

**Comment by alphaklp** [comment]
I unfortunately dont have any more as the error makes the .net Core app crash and restart - so I cannot grap further information

**Comment by alphaklp** [comment]
I actually seems it is related to the maximum size. I will validate and update the issue. thanks so far

**Comment by feinoujc** [comment]
@alphaklp any updates?

**Comment by alphaklp** [comment]
the issues was that the attachment grew over the allowed size when base64 encoded. 
a hard error but the core problem was business related and not the api
